-- Seed how-to library. URLs are placeholders to be swapped for Maman's own
-- clinician-reviewed videos before launch.
insert into public.learn_videos
  (category, title_en, title_fr, description_en, description_fr, url, duration_min, sort_order)
values
  ('injections', 'How to do a subcutaneous injection',
   'Comment faire une injection sous-cutanée',
   'A calm, step-by-step walkthrough for belly injections.',
   'Un guide calme, étape par étape, pour les injections au ventre.',
   'https://www.youtube.com/results?search_query=subcutaneous+ivf+injection+tutorial', 4, 1),
  ('injections', 'Mixing your medication safely',
   'Mélanger votre médicament en toute sécurité',
   'How to reconstitute and draw up your dose without waste.',
   'Comment reconstituer et prélever votre dose sans gaspillage.',
   'https://www.youtube.com/results?search_query=ivf+medication+mixing+tutorial', 6, 2),
  ('injections', 'The trigger shot, explained',
   'L''injection déclencheuse, expliquée',
   'Timing is everything. What the trigger does and why the hour matters.',
   'Le timing est primordial. Ce que fait le déclencheur et pourquoi l''heure compte.',
   'https://www.youtube.com/results?search_query=ivf+trigger+shot+explained', 5, 3),
  ('medications', 'Understanding your protocol',
   'Comprendre votre protocole',
   'Stimulation, suppression, support: what each medication is for.',
   'Stimulation, suppression, soutien : à quoi sert chaque médicament.',
   'https://www.youtube.com/results?search_query=ivf+protocol+medications+explained', 8, 4),
  ('medications', 'Storing your meds',
   'Conserver vos médicaments',
   'Fridge or room temperature? A quick guide to keeping meds safe.',
   'Frigo ou température ambiante ? Un guide rapide pour conserver vos médicaments.',
   'https://www.youtube.com/results?search_query=ivf+medication+storage', 3, 5),
  ('procedures', 'What happens at egg retrieval',
   'Ce qui se passe à la ponction',
   'A gentle overview of the retrieval day, start to finish.',
   'Un aperçu doux de la journée de ponction, du début à la fin.',
   'https://www.youtube.com/results?search_query=ivf+egg+retrieval+what+to+expect', 7, 6),
  ('procedures', 'Embryo transfer day',
   'Le jour du transfert',
   'What to expect during and after your transfer.',
   'À quoi s''attendre pendant et après votre transfert.',
   'https://www.youtube.com/results?search_query=ivf+embryo+transfer+what+to+expect', 6, 7),
  ('emotional', 'The two-week wait',
   'L''attente de deux semaines',
   'Real talk and grounding tools for the hardest stretch.',
   'Une vraie discussion et des outils d''ancrage pour la période la plus difficile.',
   'https://www.youtube.com/results?search_query=ivf+two+week+wait+coping', 9, 8);
